# .streamlit/config.toml
# Configuration Streamlit pour optimiser les performances

[theme]
primaryColor = "#2563eb"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false